[project]
name = "diffusion"
version = "0.1.0"
description = "Diffusion model environment for nyl12 loop engineering"
authors = []
platforms = ["linux-64"]

channels = [
    "pytorch",
    "conda-forge",
    "nvidia",
    "https://conda.rosettacommons.org",
    "protein-design",
    "dglteam/label/cu118",
    "pyg",
    "bioconda",
]
channel-priority = "disabled"

[environments]
rf = ["rf"]
ligand = ["ligand"]
boltz = ["boltz"]

[dependencies]
   python = "3.9.*"
   pytest = "*"
   jinja2 = "*"
   hydra-core = "*"

[feature.boltz.dependencies]
    mmseqs2 = "*"

[feature.rf.dependencies]
    rf_diffusion_all_atom = "*"

[feature.ligand.pypi-dependencies]
    pd-ligand-mpnn = ">=0.1.2"


[feature.ligand.tasks]
run-ligand = "run-ligand"

[feature.rf.tasks]
run-inference = "run-inference"
