[project]
name = "diffusion"
version = "0.1.0"
description = "Diffusion model environment for nyl12 loop engineering"
authors = []
platforms = ["linux-64"]

channels = [
    "pytorch",
    "conda-forge",
    "nvidia",
    "https://conda.rosettacommons.org",
    "protein-design",
    "dglteam/label/cu118",
    "pyg",
]
channel-priority = "disabled"

[environments]
rf = ["rf"]
ligand = ["ligand"]

[dependencies]
   python = "3.9.*"

[feature.rf.dependencies]
    rf_diffusion_all_atom = "*"
    pytest = "*"
    jinja2 = "*"

[feature.ligand.pypi-dependencies]
    pd-ligand-mpnn = "*"

[feature.ligand.tasks]
run-ligand = "run-ligand"

[feature.rf.tasks]
run-inference = "run-inference"