[project]
name = "diffusion"
version = "0.1.0"
description = "Diffusion model environment for nyl12 loop engineering"
authors = []
platforms = ["linux-64"]

channels = [
    "pytorch",
    "conda-forge",
    "nvidia",
    "https://conda.rosettacommons.org",
    "protein-design",
    "dglteam/label/cu118",
    "pyg",
    "bioconda",
    "schrodinger"
]
channel-priority = "disabled"

[environments]
rf = ["rf"]
ligand = ["ligand"]
colabfold = ["colabfold"]
boltz = ["boltz"]
pymol = ["pymol"]

[dependencies]

[feature.boltz.dependencies]
    python = "3.10.*"
    pytest = "*"
    jinja2 = "*"


[feature.pymol.dependencies]
    python = "3.10.*"
    pymol-bundle = "*"
    pandas = "*"
    natsort = "*"
    tabulate = "*"
    hydra-core = "*"

[feature.colabfold.dependencies]
    python = "3.10.*"
    mmseqs2 = "*"

[feature.colabfold.pypi-options]
index-url = "https://pypi.org/simple"
extra-index-urls = ["https://example.com/simple"]
find-links = [{url= 'https://storage.googleapis.com/jax-releases/jax_cuda_releases.html'}]

[feature.colabfold.pypi-dependencies]
    colabfold = { git = "git+https://github.com/sokrypton/ColabFold", extras=["alpafold"] }
    jax = {version=">=0.3.8,<0.4",extras=["cuda"]}

[feature.boltz.pypi-dependencies]
    boltz = {version="*",extras=["cuda"]}
    hydra-core = "*"


[feature.rf.dependencies]
    rf_diffusion_all_atom = "*"

[feature.ligand.dependencies]
    python = "3.9.*"
    hydra-core = "*"

[feature.ligand.pypi-dependencies]
    pd-ligand-mpnn = ">=0.1.2"

[feature.ligand.tasks]
    run-ligand = "run-ligand"

[feature.rf.tasks]
    run-inference = "run-inference"

[feature.boltz.tasks]
    boltz = "boltz"
